#!/bin/bash

if [ $# -eq 0 ]; then
  >&2 echo 'usage: bumpPkgrel [-n] $pkg1 $pkg2 $pkg3 ...'
  exit 1
fi

if [ "x$1" = 'x-n' ]; then
  commit=false
  shift
else
  commit=true
fi

if [ $# -eq 1 ]; then

  cd "$(dirname "$0")"

  pkg="${1%/}"
  eval "$(
    grep '^pkgrel=' "${pkg}/PKGBUILD"
  )"
  sed -i '
    s@^\(pkgrel=\)\('"'"'\?\)[0-9]\+\2$@\1'"$((pkgrel+1))"'@
  ' "${pkg}/PKGBUILD"
  if ${commit}; then
    git commit "${pkg}/PKGBUILD" -m "${pkg}: rebuild"
  fi

else

  printf '%s\n' "$@" \
    | xargs -rn1 "$0"

fi
