#!/bin/bash

if [ $# -eq 0 ]; then
  >&2 echo 'usage: bumpPkgrel [-n] [-p /tmp/provided] $pkg1 $pkg2 $pkg3 ...'
  exit 1
fi

if [ "x$1" = 'x-n' ]; then
  commit=false
  commit_flag='-n'
  shift
else
  commit=true
  commit_flag=''
fi

if [ "x$1" = 'x-p' ]; then
  shift
  provided="$2"
  shift
else
  provided=$("${0%/*}/liste-verfuegbare-Versionen")
  trap 'rm -f "${provided}"' EXIT
fi

pin_dependency() {
  sed '
    s/>\?=.*$//
    /^$/d
  ' \
  | sort -k1,1 \
  | join -1 1 -2 2 - "${provided}" \
  | sed '
    s/^\(\S\+\) \(\S\+\)$/'"${1}'"'\1=\2'"'"'/
    s/^\(\s*'"'"'glibc\)=/\1>=/
    t
    d
  '
}

if [ $# -eq 1 ]; then

  cd "$(dirname "$0")"

  pkg="${1%/}"
  cd "${pkg}"
  while IFS=$(printf '\n') read -r line; do
    if printf '%s\n' "${line}" \
    | grep -q '^\s*pkgrel='; then
      eval "${line}"
      printf '%s=%s\n' "${line%%=*}" "$((pkgrel+1))"
      continue
    fi
    if printf '%s\n' "${line}" \
    | grep -q '^\s*_pinned_dependencies=('; then
      space="${line%%_pinned_dependencies=(}"
      printf '%s_pinned_dependencies=(\n' "${space}"
      line="${line#*_pinned_dependencies=(}"
      {
        while ! printf '%s\n' "${line}" \
        | grep -qF ')'; do
          printf '%s\n' ${line%%#*}
          IFS=$(printf '\n') read -r line
        done
        printf '%s\n' ${line%%)*}
      } \
      | sed '
        s/^\(["'"'"']\)\(\S\+\)\1$/\2/
      ' \
      | pin_dependency "${space}  "
      printf '%s)%s\n' "${space}" "${line#*)}"
      continue
    fi
    printf '%s\n' "${line}"
  done \
  < 'PKGBUILD' \
  | sponge 'PKGBUILD'
  if ${commit}; then
    if [ -d '.git' ] || [ -f '.git' ]; then
      makepkg --printsrcinfo > .SRCINFO
      git commit 'PKGBUILD' '.SRCINFO' -m "${pkg}: rebuild"
      for remote in $(
        git remote
      ); do
        git push "${remote}" || exit 1
      done
      cd ..
      git commit "${pkg}" -m "${pkg}: rebuild"
    else
      git commit 'PKGBUILD' -m "${pkg}: rebuild"
    fi
  fi

else

  printf '%s\n' "$@" \
    | xargs -rn1 "$0" ${commit_flag} -p "${provided}"

fi
